Add -h as a short alias for --help
google/argh pull request #106
Opened 2021-09-01 05:49 UTC by aminya

2021-09-01 05:52 UTC, aminya commented
@googlebot I signed it!

2022-01-22 15:26 UTC, pjmp approved these changes

2023-01-12 16:57 UTC, LeoDog896 approved these changes
LGTM!

2023-10-19 23:42 UTC, sadmac7000 requested changes
I don't think we can change something this fundamental without having at least the option for the old behavior. My preference would be that it default to off.

2023-10-19 23:49 UTC, aminya commented
@sadmac7000 I submitted this pull request in 2021. After these years, is it worth making this simple change configurable? If I was the maintainer, I would have merged it and bumped up the major version.

2023-10-19 23:49 UTC, aminya commented
@sadmac7000 I submitted this pull request in 2021. After these years, is it worth making this simple change configurable? If I was the maintainer, I would have merged it and bumped up the major version.

2023-10-23 01:44 UTC, sadmac7000 commented
argh exists specifically to implement the Fuchsia command line argument guidelines. Breaking behaviors outside of those guidelines need more than just a major revision bump. They need an update to the guidelines or to be disabled by default.

2023-11-02 22:38 UTC, aminya commented
@sadmac7000 Where is the Fuschia documentation so that I can make the same pull request for that?

2023-11-06 23:16 UTC, sadmac7000 commented
The guidelines are documented in Google's git hosting here: https://fuchsia.googlesource.com/fuchsia/+/refs/heads/main/docs/development/api/cli.md

2023-11-12 14:08 UTC, aminya commented
@sadmac7000 Reimplemented the help trigger logic to make it configurable through attributes.

2023-11-12 17:59 UTC, sadmac7000 approved these changes

2023-11-12 17:59 UTC, sadmac7000 commented
Looks good. Looks like there's a merge conflict. Mind rebasing?

2023-11-12 21:37 UTC, aminya commented
@sadmac7000 You're welcome. The branch is already rebased. I noticed the GitHub UI can be outdated, so maybe refresh your page.

2023-11-13 17:33 UTC, sadmac7000 commented
It's still claiming the branch cannot be rebased due to conflicts and won't let me merge. I refreshed a few times. I'll look again later in case it's a transient error.

2023-11-13 21:57 UTC, sadmac7000 commented
I had to pull it down and manually rearrange it. In the future, please rebase your changes when you need to update rather than merging in upstream. It confuses github.

2023-11-13 21:57 UTC, merged