Support multiline docs
google/argh pull request #133
Opened 2022-07-15 20:10 UTC by Timmmm

Adds basic support for multiline docstrings. The rule is basically if a line starts with an alphabetic character then it is joined to the previous line.

Fixes #121
Fixes #128

2022-11-10 18:02 UTC, sadmac7000 requested changes

2022-11-11 14:33 UTC, Timmmm commented on argh_derive/src/parse_attrs.rs
> +    let new_line = match new_line.bytes().next() {
Ah yeah good point.

2022-11-11 14:33 UTC, Timmmm commented on argh_derive/src/parse_attrs.rs
> +    let line_starts_with_letter = new_line.bytes().next().map(|c| c.is_ascii_alphabetic()).unwrap_or(false);
Yeah that makes sense. I changed it to alphanumeric too to be a bit more lenient.

2023-07-25 20:44 UTC, sadmac7000 approved these changes

2023-10-19 23:38 UTC, sadmac7000 commented
This could land if rebased and reformatted.

2023-11-16 12:12 UTC, Timmmm commented
I have rebased, formatted and squashed it. Unfortunately there are two issues I found:

1. The `escaped_doc_comment_description` test fails due to an extra newline.
2. You can't start a description with a capital letter which seems overly restrictive and weird for a multi-line paragraph.

I have stopped using `argh` and switch to Clap, so I'll leave you to decide how to deal with this (fix those issues or just close this).

2024-08-08 21:08 UTC, closed without merging