feat: suggest fuzzy matches in case on unrecognized arguments
google/argh pull request #180
Opened 2023-11-12 22:32 UTC by aminya

2023-11-12 22:43 UTC, aminya commented on argh/src/lib.rs
> +                    &["--help".to_owned(), "help".to_owned()],
After merging #106, this can be updated to include all the help triggers.

2023-11-13 22:01 UTC, sadmac7000 requested changes
Mostly this looks good. Please rebase and add your changes to account for help triggers as you suggested.

2023-11-13 22:12 UTC, aminya commented on argh/src/lib.rs
> +                    &["--help".to_owned(), "help".to_owned()],
Fixed in https://github.com/google/argh/pull/180/commits/364f7a85dacf56c70f0977e6999cea4980f7aec6

2023-11-13 22:13 UTC, sadmac7000 approved these changes

2023-11-13 22:14 UTC, merged